// Modified from version generated by Gemini
package com.uccnasc.xr;

import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import com.google.mlkit.vision.common.InputImage;
import com.google.mlkit.vision.text.TextRecognition;
import com.google.mlkit.vision.text.TextRecognizer;
import com.google.mlkit.vision.text.latin.TextRecognizerOptions;
import com.unity3d.player.UnityPlayer;

public class TextPlugin {
    public static void processImage(final byte[] imageBytes, final String gameObject, final String callback) {
        new Thread(() -> {
            try {
                Bitmap bitmap = BitmapFactory.decodeByteArray(imageBytes, 0, imageBytes.length);
                if (bitmap == null) {
                    UnityPlayer.UnitySendMessage(gameObject, callback, "ERROR:Failed to decode image.");
                    return;
                }

                InputImage image = InputImage.fromBitmap(bitmap, 0);
                TextRecognizer recognizer = TextRecognition.getClient(TextRecognizerOptions.DEFAULT_OPTIONS);

                recognizer.process(image)
                    .addOnSuccessListener(visionText -> {
                        String detectedText = visionText.getText();
                        if (detectedText.isEmpty()) {
                            UnityPlayer.UnitySendMessage(gameObject, callback, "ERROR:No text detected.");
                            return;
                        }
                        UnityPlayer.UnitySendMessage(gameObject, callback, "SUCCESS:" + detectedText);
                    })
                    .addOnFailureListener(e -> 
                        UnityPlayer.UnitySendMessage(gameObject, callback, "ERROR:" + e.getMessage())
                    );
                
            } catch (Exception e) {
                UnityPlayer.UnitySendMessage(gameObject, callback, "ERROR:" + e.getMessage());
            }
        }).start();
    }
}
