// Modified from version generated by Gemini
package com.uccnasc.xr;

import com.google.mlkit.common.model.DownloadConditions;
import com.google.mlkit.nl.languageid.LanguageIdentification;
import com.google.mlkit.nl.languageid.LanguageIdentifier;
import com.google.mlkit.nl.translate.TranslateLanguage;
import com.google.mlkit.nl.translate.Translation;
import com.google.mlkit.nl.translate.Translator;
import com.google.mlkit.nl.translate.TranslatorOptions;
import com.unity3d.player.UnityPlayer;

public class TranslatePlugin {
    public static void translateText(final String textToTranslate, final String gameObject, final String callback) {
        LanguageIdentifier languageIdentifier = LanguageIdentification.getClient();
        
        languageIdentifier.identifyLanguage(textToTranslate)
            .addOnSuccessListener(languageCode -> {
                if (languageCode.equals("und")) {
                    UnityPlayer.UnitySendMessage(gameObject, callback, "ERROR:Language detection failed (undetermined text).");
                    return;
                }
                
                String resolvedSourceLang = TranslateLanguage.fromLanguageTag(languageCode);
    
                if (resolvedSourceLang == null) {
                    UnityPlayer.UnitySendMessage(gameObject, callback, "ERROR:Detected language (" + languageCode + ") is unsupported.");
                    return;
                }

                TranslatorOptions options = new TranslatorOptions.Builder()
                        .setSourceLanguage(resolvedSourceLang) 
                        .setTargetLanguage(TranslateLanguage.ENGLISH) // Note: Hardcoded target language
                        .build();
                        
                final Translator translator = Translation.getClient(options);
                DownloadConditions conditions = new DownloadConditions.Builder().requireWifi().build();

                translator.downloadModelIfNeeded(conditions)
                        .addOnSuccessListener(v -> {
                            translator.translate(textToTranslate)
                                .addOnSuccessListener(translatedText -> {
                                    UnityPlayer.UnitySendMessage(gameObject, callback, "SUCCESS:" + translatedText);
                                    translator.close();
                                })
                                .addOnFailureListener(e -> {
                                    UnityPlayer.UnitySendMessage(gameObject, callback, "ERROR:Translation error: " + e.getMessage());
                                    translator.close();
                                });
                        })
                        .addOnFailureListener(e -> {
                            UnityPlayer.UnitySendMessage(gameObject, callback, "ERROR:Model download error: " + e.getMessage());
                            translator.close();
                        });
            })
            .addOnFailureListener(e -> 
                UnityPlayer.UnitySendMessage(gameObject, callback, "ERROR:Language detection error: " + e.getMessage())
            );
    }
}
