// Modified from version generated by Gemini
package com.uccnasc.xr; // Customize the package name as desired

import android.app.Activity;
import android.speech.tts.TextToSpeech;
import com.unity3d.player.UnityPlayer;
import java.util.Locale;

public class TtsPlugin {
    private static TextToSpeech tts = null;
    private static boolean initialized = false;

    public static void initialize() {
        final Activity activity = UnityPlayer.currentActivity;
        activity.runOnUiThread(() -> {
            if (tts != null) return;

            tts = new TextToSpeech(activity, new TextToSpeech.OnInitListener() {
                @Override
                public void onInit(int status) {
                    if (status == TextToSpeech.SUCCESS) {
                        // Sets default engine language to US English
                        int result = tts.setLanguage(Locale.US);
                        if (result != TextToSpeech.LANG_MISSING_DATA && result != TextToSpeech.LANG_NOT_SUPPORTED) {
                            initialized = true;
                        }
                    }
                }
            });
        });
    }

    public static void speak(final String text) {
        if (tts == null || !initialized) return;

        final Activity activity = UnityPlayer.currentActivity;
        activity.runOnUiThread(() -> {
            // QUEUE_FLUSH interrupts any current speech to play the new text immediately
            tts.speak(text, TextToSpeech.QUEUE_FLUSH, null, "UnityTTS");
        });
    }

    public static void shutdown() {
        final Activity activity = UnityPlayer.currentActivity;
        activity.runOnUiThread(() -> {
            if (tts == null) return;

            tts.stop();
            tts.shutdown();
            tts = null;
            initialized = false;
        });
    }
}
