// Modified from version generated by Gemini
package com.uccnasc.xr;

import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.speech.RecognitionListener;
import android.speech.RecognizerIntent;
import android.speech.SpeechRecognizer;
import com.unity3d.player.UnityPlayer;
import java.util.ArrayList;

public class VoicePlugin {
    private static SpeechRecognizer speechRecognizer = null;
    private static Intent recognizerIntent = null;
    private static boolean isListening = false;

    public static void startListening(final String gameObject, final String callbackMethod) {
        final Activity activity = UnityPlayer.currentActivity;
        activity.runOnUiThread(() -> {
            if (speechRecognizer == null) {
                speechRecognizer = SpeechRecognizer.createSpeechRecognizer(activity);
                
                recognizerIntent = new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);
                recognizerIntent.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL, RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);
                recognizerIntent.putExtra(RecognizerIntent.EXTRA_PARTIAL_RESULTS, true);

                speechRecognizer.setRecognitionListener(new RecognitionListener() {
                    @Override public void onReadyForSpeech(Bundle params) {}
                    @Override public void onBeginningOfSpeech() {}
                    @Override public void onRmsChanged(float rmsdB) {}
                    @Override public void onBufferReceived(byte[] buffer) {}
                    @Override public void onEndOfSpeech() {}
                    
                    @Override
                    public void onError(int error) {
                        isListening = false;
                        UnityPlayer.UnitySendMessage(gameObject, callbackMethod, "ERROR:" + error);
                    }

                    @Override
                    public void onResults(Bundle results) {
                        isListening = false;
                        ArrayList<String> matches = results.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION);
                        if (matches != null && !matches.isEmpty()) {
                            UnityPlayer.UnitySendMessage(gameObject, callbackMethod, "FINAL:" + matches.get(0));
                        }
                    }

                    @Override
                    public void onPartialResults(Bundle partialResults) {
                        ArrayList<String> matches = partialResults.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION);
                        if (matches != null && !matches.isEmpty()) {
                            UnityPlayer.UnitySendMessage(gameObject, callbackMethod, "PARTIAL:" + matches.get(0));
                        }
                    }

                    @Override public void onEvent(int eventType, Bundle params) {}
                });
            } else {
                speechRecognizer.cancel();
            }

            isListening = true;
            speechRecognizer.startListening(recognizerIntent);
        });
    }

    public static void stopListening() {
        final Activity activity = UnityPlayer.currentActivity;
        activity.runOnUiThread(() -> {
            if (speechRecognizer != null && isListening) {
                speechRecognizer.stopListening();
            }
            isListening = false;
        });
    }
}
